import fs from 'fs/promises';
import path from 'path';
import { logger } from '../utils/logger.js';

interface PackageInput {
  threadId: string;
  appName: string;
  eiapCode: string;
  workflowJson: Record<string, unknown>;
  targetPlatform: string;
}

interface ValidationResult {
  valid: boolean;
  errors: string[];
  checks: string[];
}

export interface RappPackageResult {
  packageId: string;
  packagePath: string;
  archivePath: string;
  validation: ValidationResult;
}

export class RappPackagerService {
  static async createPackage(input: PackageInput): Promise<RappPackageResult> {
    const packageId = `${input.threadId}-${Date.now()}`;
    const packageRoot = path.join(process.cwd(), 'generated', 'rapp', packageId);
    const helmDir = path.join(packageRoot, 'helm', 'templates');

    await fs.mkdir(helmDir, { recursive: true });

    await fs.writeFile(path.join(packageRoot, 'app.py'), input.eiapCode, 'utf-8');
    await fs.writeFile(
      path.join(packageRoot, 'requirements.txt'),
      [
        'pandas>=2.0.0',
        'numpy>=1.24.0',
        'pyyaml>=6.0',
        'eiap-adaptor>=1.0.0',
      ].join('\n') + '\n',
      'utf-8'
    );

    const manifest = {
      name: input.appName,
      version: '1.0.0',
      platform: input.targetPlatform,
      scenario: 'prb_qrxlevmin_v1',
      entrypoint: 'app.py',
      threadId: input.threadId,
      generatedAt: new Date().toISOString(),
      artifacts: ['app.py', 'requirements.txt', 'helm/', 'workflow.json'],
    };
    await fs.writeFile(path.join(packageRoot, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf-8');
    await fs.writeFile(path.join(packageRoot, 'workflow.json'), JSON.stringify(input.workflowJson, null, 2), 'utf-8');
    await fs.writeFile(
      path.join(packageRoot, 'helm', 'Chart.yaml'),
      [
        'apiVersion: v2',
        `name: ${this.sanitizeHelmName(input.appName)}`,
        'description: Telecom rApp generated by conversational builder',
        'type: application',
        'version: 1.0.0',
        'appVersion: "1.0.0"',
      ].join('\n') + '\n',
      'utf-8'
    );
    await fs.writeFile(
      path.join(packageRoot, 'helm', 'values.yaml'),
      [
        'replicaCount: 1',
        'image:',
        '  repository: naavik/generated-rapp',
        '  tag: latest',
        '  pullPolicy: IfNotPresent',
        'service:',
        '  type: ClusterIP',
        '  port: 8080',
      ].join('\n') + '\n',
      'utf-8'
    );
    await fs.writeFile(
      path.join(helmDir, 'deployment.yaml'),
      [
        'apiVersion: apps/v1',
        'kind: Deployment',
        'metadata:',
        `  name: ${this.sanitizeHelmName(input.appName)}`,
        'spec:',
        '  replicas: {{ .Values.replicaCount }}',
        '  selector:',
        '    matchLabels:',
        `      app: ${this.sanitizeHelmName(input.appName)}`,
        '  template:',
        '    metadata:',
        '      labels:',
        `        app: ${this.sanitizeHelmName(input.appName)}`,
        '    spec:',
        '      containers:',
        '        - name: rapp-runtime',
        '          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"',
        '          imagePullPolicy: {{ .Values.image.pullPolicy }}',
        '          ports:',
        '            - containerPort: {{ .Values.service.port }}',
      ].join('\n') + '\n',
      'utf-8'
    );

    // We keep this as a deterministic artifact path for integrations that expect CSAR-like output.
    const archivePath = path.join(packageRoot, 'package.csar');
    await fs.writeFile(
      archivePath,
      JSON.stringify(
        {
          packageId,
          packageRoot,
          manifest,
          files: [
            'app.py',
            'requirements.txt',
            'manifest.json',
            'workflow.json',
            'helm/Chart.yaml',
            'helm/values.yaml',
            'helm/templates/deployment.yaml',
          ],
        },
        null,
        2
      ),
      'utf-8'
    );

    const validation = await this.validatePackage(packageRoot);
    logger.info('rApp package created', { packageId, packageRoot, valid: validation.valid });

    return {
      packageId,
      packagePath: packageRoot,
      archivePath,
      validation,
    };
  }

  static async validatePackage(packageRoot: string): Promise<ValidationResult> {
    const errors: string[] = [];
    const checks: string[] = [];

    const requiredFiles = [
      'app.py',
      'requirements.txt',
      'manifest.json',
      'workflow.json',
      'helm/Chart.yaml',
      'helm/values.yaml',
      'helm/templates/deployment.yaml',
      'package.csar',
    ];

    for (const rel of requiredFiles) {
      const full = path.join(packageRoot, rel);
      try {
        await fs.access(full);
        checks.push(`exists:${rel}`);
      } catch {
        errors.push(`Missing required file: ${rel}`);
      }
    }

    // Manifest schema checks
    try {
      const manifestPath = path.join(packageRoot, 'manifest.json');
      const manifestRaw = await fs.readFile(manifestPath, 'utf-8');
      const manifest = JSON.parse(manifestRaw);
      const requiredManifestFields = ['name', 'version', 'platform', 'entrypoint', 'generatedAt'];
      for (const field of requiredManifestFields) {
        if (!manifest[field]) errors.push(`manifest.json missing required field: ${field}`);
      }
      checks.push('manifest:json-parse');
    } catch (error: any) {
      errors.push(`manifest.json invalid: ${error.message}`);
    }

    // Helm template checks
    try {
      const chart = await fs.readFile(path.join(packageRoot, 'helm', 'Chart.yaml'), 'utf-8');
      if (!chart.includes('apiVersion: v2') || !chart.includes('type: application')) {
        errors.push('helm/Chart.yaml missing required Helm chart fields');
      } else {
        checks.push('helm:chart-fields');
      }

      const deployment = await fs.readFile(path.join(packageRoot, 'helm', 'templates', 'deployment.yaml'), 'utf-8');
      if (!deployment.includes('kind: Deployment') || !deployment.includes('{{ .Values.image.repository }}')) {
        errors.push('helm/templates/deployment.yaml missing deployment structure or templated image');
      } else {
        checks.push('helm:deployment-template');
      }
    } catch (error: any) {
      errors.push(`Helm validation failed: ${error.message}`);
    }

    // Dependency sanity
    try {
      const requirements = await fs.readFile(path.join(packageRoot, 'requirements.txt'), 'utf-8');
      const deps = requirements
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean);
      if (deps.length < 3) errors.push('requirements.txt has too few dependencies');
      if (!deps.some((dep) => dep.toLowerCase().startsWith('eiap-adaptor'))) {
        errors.push('requirements.txt missing eiap-adaptor dependency');
      } else {
        checks.push('requirements:eiap-adaptor');
      }
    } catch (error: any) {
      errors.push(`requirements.txt validation failed: ${error.message}`);
    }

    return {
      valid: errors.length === 0,
      errors,
      checks,
    };
  }

  private static sanitizeHelmName(appName: string): string {
    return appName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/--+/g, '-').replace(/^-|-$/g, '') || 'generated-rapp';
  }
}
