/**
 * Hardcoded scenario matcher for non-demo mode
 * When user messages match known scenarios, return scripted response + workflow + code
 * instead of calling the LLM (ensures reliable demo flow even without OpenAI)
 */
import { DEMO_SCENARIOS, getDemoScenario, type DemoScenario } from './demo-conversations.js';
import { logger } from '../utils/logger.js';

export interface ScenarioMatchResult {
  matched: true;
  scenarioId: string;
  assistantResponse: string;
  workflow?: any;
  generatedCode?: string;
  isComplete: boolean;
  nextTurn?: number;
}

/**
 * Keyword patterns for "complete" single-message matches (user pastes everything at once)
 * Must contain enough of these to trigger
 */
const COMPLETE_PATTERNS: Record<string, string[]> = {
  'prb-optimization': [
    'congestion', 'overload', 'prb', '90', 'qrxlevmin', 'qrxlev',
    '4g', '4G', 'eutran', '2 db', '2db', 'shrink', 'neighbor', 'cells'
  ],
  'handover-optimization': [
    'handover', 'failure', 'drop', '5%', 'a3offset', 'a3Offset', 'decrease'
  ],
  'rrc-failure-fix': [
    'rrc', 'connection', 'failure', '3%', 'maxharqtx', 'harq', 'retransmit'
  ],
  'data-drop-mitigation': [
    'data drop', 'drop rate', '2%', 'pdcp', 'buffer', 'scheduling'
  ],
  '5g-capacity-boost': [
    '5g', 'throughput', 'carrier aggregation', 'prb', '60', 'maxNumScells', 'scell'
  ],
};

/**
 * Normalize text for matching (lowercase, collapse whitespace)
 */
function normalize(text: string): string {
  return text.toLowerCase().replace(/\s+/g, ' ').trim();
}

/**
 * Check if a message fully matches a scenario (user pasted complete requirements)
 */
function matchCompleteRequest(message: string): DemoScenario | null {
  const normalized = normalize(message);
  
  for (const scenario of DEMO_SCENARIOS) {
    const patterns = COMPLETE_PATTERNS[scenario.id];
    if (!patterns) continue;
    
    const matchCount = patterns.filter(p => normalized.includes(p.toLowerCase())).length;
    const threshold = Math.min(3, Math.ceil(patterns.length * 0.25));
    if (matchCount >= threshold) {
      logger.info('Scenario matcher: complete match', { scenarioId: scenario.id, matchCount });
      return scenario;
    }
  }
  return null;
}

/**
 * Check if conversation + new message matches next turn in a scenario
 */
function matchNextTurn(
  existingMessages: Array<{ role: string; content: string }>,
  newMessage: string
): { scenario: DemoScenario; turn: number } | null {
  const userMessages = [...existingMessages.filter(m => m.role === 'user'), { role: 'user', content: newMessage }]
    .map(m => (m as { content: string }).content);
  
  for (const scenario of DEMO_SCENARIOS) {
    const conv = scenario.conversation;
    const scenarioUserMsgs = conv.filter(m => m.role === 'user').map(m => m.content);
    
    if (userMessages.length > scenarioUserMsgs.length) continue;
    
    let matchedTurn = -1;
    for (let i = 0; i < userMessages.length; i++) {
      const userNorm = normalize(userMessages[i]);
      const scriptNorm = normalize(scenarioUserMsgs[i]);
      if (userNorm.includes(scriptNorm) || scriptNorm.includes(userNorm) || 
          (userNorm.length > 10 && scriptNorm.length > 10 && 
           (userNorm.includes(scriptNorm.slice(0, 20)) || scriptNorm.includes(userNorm.slice(0, 20))))) {
        matchedTurn = i;
      } else {
        break;
      }
    }
    if (matchedTurn >= 0 && matchedTurn === userMessages.length - 1) {
      return { scenario, turn: matchedTurn };
    }
  }
  return null;
}

/**
 * Generate Python code from demo workflow (matches frontend demo code style)
 */
function generateCodeFromWorkflow(workflow: any): string {
  const name = (workflow.name || 'GeneratedApp').replace(/\s+/g, '');
  const desc = workflow.description || 'Telecom automation app';
  const nodes = workflow.nodes || [];
  const cellType = nodes.some((n: any) => n.data?.entityType === 'NRCellDU') ? 'NRCellDU' : 'EUtranCell';
  const cellLabel = cellType === 'NRCellDU' ? '5G' : '4G';
  const condNodes = nodes.filter((n: any) => n.type === 'condition');
  const actionNodes = nodes.filter((n: any) => n.type === 'action' && n.data?.parameter);
  const condition = condNodes[0]?.data?.condition || 'kpi_value > threshold';
  const param = actionNodes[0]?.data?.parameter || 'parameter';
  const change = String(actionNodes[0]?.data?.change || actionNodes[0]?.data?.value || '+1');
  const kpi = actionNodes[0]?.data?.kpi || 'avg_dl_prb_util';
  const newValueExpr = /^[+-]\d+/.test(change) ? `current_value ${change}` : change;

  return `"""
${desc}
Auto-generated by Naavik AppGen Agent
"""

from adaptors.eiap.eiap_adaptor import EIAPAdaptor as DataAdapter
import json
from datetime import datetime, timezone
from collections import defaultdict

class ${name}:
    def __init__(self):
        self.data_adapter = DataAdapter()
        self.report = defaultdict(dict)
        self.app_name = "${name}"
        
    def execute(self):
        """Main execution logic"""
        print(f"🚀 Starting {self.app_name}")
        
        cell_ids = self.data_adapter.get_cm_handle_ids(
            "/domains/RAN/entity-types/${cellType}/entities?targetFilter=/sourceIds;/attributes"
        )
        
        print(f"📡 Found {len(cell_ids)} ${cellLabel} cells")
        actions_taken = 0
        
        for i, cmhandle_id in enumerate(cell_ids):
            print(f"  Processing cell {i+1}/{len(cell_ids)}: {cmhandle_id}")
            
            try:
                kpi_data = self.data_adapter.get(cmhandle_id, "kpi", "${kpi}")
                
                if kpi_data and ${condition.replace(/and/g, ' and ')}:
                    current_value = self.data_adapter.get(cmhandle_id, "${cellType}", "${param}")
                    new_value = ${newValueExpr}
                    self.data_adapter.update(cmhandle_id, "${cellType}", "${param}", new_value)
                    self.report[cmhandle_id]['action'] = f"${param}: {current_value} → {new_value}"
                    self.report[cmhandle_id]['timestamp'] = datetime.now(timezone.utc).isoformat()
                    actions_taken += 1
                else:
                    self.report[cmhandle_id]['action'] = "No action needed"
                    
            except Exception as e:
                print(f"    ⚠️  Error: {e}")
                self.report[cmhandle_id]['error'] = str(e)
        
        print(f"✅ Completed! Actions taken: {actions_taken}/{len(cell_ids)}")
        return self.report

if __name__ == "__main__":
    app = ${name}()
    result = app.execute()
    with open("${name.toLowerCase()}_report.json", "w") as f:
        json.dump(result, f, indent=2)
    print("📊 Report saved")
`;
}

/**
 * Try to match user input to a hardcoded scenario. Used in non-demo mode.
 */
export function matchHardcodedScenario(
  existingMessages: Array<{ role: string; content: string }>,
  newMessage: string
): ScenarioMatchResult | null {
  const combinedText = [...existingMessages.map(m => m.content), newMessage].join('\n');
  
  // 1. Complete request (user pasted everything)
  const completeScenario = matchCompleteRequest(combinedText);
  if (completeScenario) {
    const lastAssistant = completeScenario.conversation
      .filter(m => m.role === 'assistant')
      .pop();
    const response = lastAssistant?.content || `Created **${completeScenario.finalWorkflow.name}**! Generating code...`;
    const code = generateCodeFromWorkflow(completeScenario.finalWorkflow);
    
    return {
      matched: true,
      scenarioId: completeScenario.id,
      assistantResponse: response,
      workflow: completeScenario.finalWorkflow,
      generatedCode: code,
      isComplete: true,
    };
  }
  
  // 2. Multi-turn: match next turn in a scenario
  const turnMatch = matchNextTurn(existingMessages, newMessage);
  if (turnMatch) {
    const { scenario, turn } = turnMatch;
    const assistantIndex = turn * 2 + 1;
    const conv = scenario.conversation;
    if (assistantIndex < conv.length) {
      const assistantMsg = conv[assistantIndex];
      const isComplete = assistantIndex === conv.length - 1;
      let workflow = undefined;
      let generatedCode = undefined;
      if (isComplete) {
        workflow = scenario.finalWorkflow;
        generatedCode = generateCodeFromWorkflow(workflow);
      }
      
      return {
        matched: true,
        scenarioId: scenario.id,
        assistantResponse: assistantMsg.content,
        workflow,
        generatedCode,
        isComplete,
        nextTurn: turn + 1,
      };
    }
  }
  
  return null;
}
