apiVersion: apps/v1
kind: Deployment
metadata:
  name: builder-bd145525da
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: builder-bd145525da
  template:
    metadata:
      labels:
        app: builder-bd145525da
    spec:
      containers:
        - name: rapp-runtime
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
